<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__defineKpi360keyPerformanceIndicators</name>
   <tag></tag>
   <elementGuidId>9955024e-925c-412c-8d3b-45a3aabbebcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='defineKpi360_keyPerformanceIndicators']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#defineKpi360_keyPerformanceIndicators</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb22884d-7e61-49e1-b073-08487ad0aac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>a6a4aeee-2eba-4d83-9695-feb5bf4ab07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a22c75f3-2c7e-4b0c-9d6f-6fb0b9e1163f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defineKpi360[keyPerformanceIndicators]</value>
      <webElementGuid>ee4bfbc4-67bb-4de3-930b-a9e0b3eb65b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defineKpi360_keyPerformanceIndicators</value>
      <webElementGuid>408f2972-8ce5-433e-b85d-dd531b8f6566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defineKpi360_keyPerformanceIndicators&quot;)</value>
      <webElementGuid>2d082ada-cd33-4728-8f4b-bfb05cb3d901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='defineKpi360_keyPerformanceIndicators']</value>
      <webElementGuid>bae6ff04-8e79-4729-b711-e26158981f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/ol/li[2]/input</value>
      <webElementGuid>8362ae47-a2a3-4c88-a838-c36e376e3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>c8242ddd-21f6-47bb-8ade-1f65d1e3c9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'defineKpi360[keyPerformanceIndicators]' and @id = 'defineKpi360_keyPerformanceIndicators']</value>
      <webElementGuid>fd0a4ffc-f3bf-477b-b2aa-e177e80c9d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
