<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__defineKpi360maxRating</name>
   <tag></tag>
   <elementGuidId>7195eb60-3096-4ee1-be7d-5f92bd78a5b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='defineKpi360_maxRating']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#defineKpi360_maxRating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a5529b-825e-46d3-94e9-a651d25724d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>4b8cf24f-8c1a-4383-b310-a7aa7bbcfdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5887424-1e5e-4703-aafc-f449779089a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defineKpi360[maxRating]</value>
      <webElementGuid>2e319199-b313-4180-b5b8-0ce9fa4503f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9c616f54-ab14-4270-a294-788cc3404bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defineKpi360_maxRating</value>
      <webElementGuid>649ce4f4-948c-406f-8297-d5109067575d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defineKpi360_maxRating&quot;)</value>
      <webElementGuid>8d70858a-9761-4d77-a385-689e8b9a829f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='defineKpi360_maxRating']</value>
      <webElementGuid>af50d217-bb3f-4b3f-bf4b-96bdb451e7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/ol/li[4]/input</value>
      <webElementGuid>e0a45700-4ca4-4e60-89dd-219c35a11341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>a1ba95b6-c26d-4701-8db4-26a710b7f16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'defineKpi360[maxRating]' and @id = 'defineKpi360_maxRating']</value>
      <webElementGuid>f2da4943-1d4a-4493-9f31-842af61cc3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
