<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make Default Scale_defineKpi360makeDefault</name>
   <tag></tag>
   <elementGuidId>693a50a8-e60a-4d50-bca3-ccaa30277e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='defineKpi360_makeDefault']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#defineKpi360_makeDefault</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de1a92b2-b1ce-4038-ab1e-5a07e1f99b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formCheckbox</value>
      <webElementGuid>30b6889a-a849-4188-b7cb-90b1d9fd49b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9e8ea385-e7b3-43d6-8356-f2a96549fe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defineKpi360[makeDefault]</value>
      <webElementGuid>f2a0982a-4cc6-4e56-909e-87a949ab1675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defineKpi360_makeDefault</value>
      <webElementGuid>50e0f9be-9557-482d-a032-bb4861ba7bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defineKpi360_makeDefault&quot;)</value>
      <webElementGuid>81927629-f690-477b-a703-d9d9fe282f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='defineKpi360_makeDefault']</value>
      <webElementGuid>e434a915-03db-4456-82a8-a23cc3134021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/ol/li[5]/input</value>
      <webElementGuid>8b0cf215-e300-4c68-a773-c60071f82a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>f9d3d852-b941-496b-aac4-4bea9d520052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'defineKpi360[makeDefault]' and @id = 'defineKpi360_makeDefault']</value>
      <webElementGuid>f49c3215-974a-4d85-9435-c065fa2b8baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
