<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__defineKpi360minRating</name>
   <tag></tag>
   <elementGuidId>dd90eae0-e927-4b3a-98fd-0f93ccfc3b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='defineKpi360_minRating']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#defineKpi360_minRating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec4f26de-a1e5-4c8c-9715-e8916ee28fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>aee935b8-9fa8-46fc-b0aa-3135b8ea52f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5dcf50bc-a126-4348-bbdd-30af1317463a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defineKpi360[minRating]</value>
      <webElementGuid>792c5402-c8b3-4139-8029-7698daea5b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f06ff933-0ace-4f95-b8d6-d197fb1f78cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defineKpi360_minRating</value>
      <webElementGuid>b10d40de-dd2f-4780-8223-f127ad0141c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defineKpi360_minRating&quot;)</value>
      <webElementGuid>dd5b3fb7-b66f-4ce0-a920-1bbf36d092fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='defineKpi360_minRating']</value>
      <webElementGuid>e3e20b7b-87ba-431f-9cca-efdcfa50a8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/ol/li[3]/input</value>
      <webElementGuid>d37ee2e1-028d-4bfe-b484-3046e17b9579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>9e36f6e5-b226-45d9-9f43-567b5b07ba75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'defineKpi360[minRating]' and @id = 'defineKpi360_minRating']</value>
      <webElementGuid>86463ac8-89d3-434a-8019-6c730bffc12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
