<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Should be less than 100 - Copy</name>
   <tag></tag>
   <elementGuidId>b7fadb3f-90b1-449a-962a-3159c6a89f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchKpi']/fieldset/ol/li[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>298498b1-ab34-4184-a5cc-f32430651dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>defineKpi360_maxRating</value>
      <webElementGuid>85e86d3c-b97c-4ccc-bf43-0681c1fa90b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fb4c91a-2f5e-47c0-8288-ad72c261a1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>3aae3487-f6ce-4d1a-9107-40d4a15e7f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Should be less than 100</value>
      <webElementGuid>06f45eb4-87cd-4bba-8af5-ee4be05dd60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchKpi&quot;)/fieldset[1]/ol[1]/li[4]/span[@class=&quot;validation-error&quot;]</value>
      <webElementGuid>0f0b053d-d67b-4a24-a26c-af54447b8c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/ol/li[4]/span</value>
      <webElementGuid>4f14615b-d6bb-4438-9a21-ee111f5c41e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[1]</value>
      <webElementGuid>a95fbe08-4aec-4f70-9c21-b722471a904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Default Scale'])[1]/preceding::span[1]</value>
      <webElementGuid>f019f5d6-f201-4376-a2c7-2036899e5fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Should be less than 100']/parent::*</value>
      <webElementGuid>5c30f093-00e0-4a6d-b6e9-5efe7bee7896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>775a46f2-2a4b-4909-b3a2-5f303ccfef04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Should be less than 100' or . = 'Should be less than 100')]</value>
      <webElementGuid>60ae10cb-e7c8-46bb-93a8-8c80193da7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
