<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__defineKpi360keyPerformanceIndicators</name>
   <tag></tag>
   <elementGuidId>303c0249-b84f-434f-9f78-965ca5f2c38b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#defineKpi360_keyPerformanceIndicators</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='defineKpi360_keyPerformanceIndicators']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e2fad7a-5faa-48aa-9e72-4dcd5acaefef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>2748888b-badb-4d86-aa65-6d3dffbab827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2202a41-926c-4716-82ea-619d51b4baa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defineKpi360[keyPerformanceIndicators]</value>
      <webElementGuid>8af3c1a0-abbc-4ec1-9a61-471864f52b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defineKpi360_keyPerformanceIndicators</value>
      <webElementGuid>0a1fb6a1-9423-4c0d-b039-c8920a05d459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;defineKpi360_keyPerformanceIndicators&quot;)</value>
      <webElementGuid>1223c26a-82e2-4f7c-8e1b-c6c3e005b6f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='defineKpi360_keyPerformanceIndicators']</value>
      <webElementGuid>85bbf43e-ded4-44ff-9451-d637ade43043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/ol/li[2]/input</value>
      <webElementGuid>5d597980-3938-4b44-8637-43018721876c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>720ab404-5608-4c6c-9db1-00235e471283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'defineKpi360[keyPerformanceIndicators]' and @id = 'defineKpi360_keyPerformanceIndicators']</value>
      <webElementGuid>4f9cf752-a58c-417b-b211-52bf9ac218aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
