<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Key Performance Indicators for Job Ti_00da0f</name>
   <tag></tag>
   <elementGuidId>65eb9a66-8b29-4de6-b4db-daf7497a4547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAdd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64485683-245e-403d-9e32-aae74128dbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88ddb4b4-a620-489e-8520-e22df13250bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>721aea02-c929-415b-aabf-a5240db1e8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAdd</value>
      <webElementGuid>e6e5444e-5d3e-44b3-bbc1-46f3fe8177d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAdd</value>
      <webElementGuid>a9423eea-d3a1-45f6-942a-d4f03a80653a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>e12fabaa-22a8-4464-abcc-70365ac6ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAdd&quot;)</value>
      <webElementGuid>7d0474d2-33cf-4ec0-a334-df8e363f840f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAdd']</value>
      <webElementGuid>eb492a40-e76d-4772-8ec8-a6d01123850d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input</value>
      <webElementGuid>98cdbdaa-8684-477b-bfce-138942402e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>a5041516-52b0-4964-9362-baa38ef6d485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnAdd' and @name = 'btnAdd']</value>
      <webElementGuid>16a3eb5a-08bc-4f97-95dd-5eb9f60bf4cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
