<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__saveBtn</name>
   <tag></tag>
   <elementGuidId>2cd36601-771c-49a0-a599-f4ead77f0c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saveBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1b15eed-3a2d-44c5-875c-27e428203986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6565952d-69fd-44e7-ae57-65a28745d6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addbutton hover</value>
      <webElementGuid>6f51a6a5-0511-45a7-ab8d-b4176bc4a3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>saveBtn</value>
      <webElementGuid>4d3b0d6a-1dfb-41c7-b5bc-91ed3784a4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveBtn</value>
      <webElementGuid>ba111135-fec5-441b-ad43-45f61c24fd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>a6177747-69ed-4061-9538-f6284c78a50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveBtn&quot;)</value>
      <webElementGuid>575121f4-758d-454a-9b8b-0ff91e025c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saveBtn']</value>
      <webElementGuid>1726b1c8-5187-4259-9189-a598ad6e848e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchKpi']/fieldset/p/input</value>
      <webElementGuid>6b5a7ea4-e30d-4f14-8aa9-8d00e1eb307d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>ee4057f9-ac21-4daf-a19f-f450e7a3a083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'saveBtn' and @id = 'saveBtn']</value>
      <webElementGuid>70335ccb-fb93-4eff-a084-7d64ce34d936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
