<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1e20218f-21b6-4310-beb0-d0bfa9918a76</testSuiteGuid>
   <testCaseLink>
      <guid>23a3e32f-f799-456b-ad44-4f1e54a1983c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven/add job</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e333a161-cad6-4203-a6dd-4daa8ddd6d0f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e333a161-cad6-4203-a6dd-4daa8ddd6d0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>title</value>
         <variableId>a543ecb7-1931-49da-a872-451e1afca0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e333a161-cad6-4203-a6dd-4daa8ddd6d0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>e915d35c-f178-4167-ac63-be371ef45d66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e333a161-cad6-4203-a6dd-4daa8ddd6d0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>cc50c580-08d3-4d3b-a4d7-99afd0348816</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
